### PR TITLE
DSP-24286 Enables Spark JobServer in Java 11

### PR DESCRIPTION
**Pull request by tiagomlalves**
Previously, we removed JVM options that have been deprecated in Java 9+ (causing warnings in Java 11) and one option that didn't exist in Java 11.
The issue with that approach was that, those options are still valid in Java 8 which is the default for DSE 6.8 and at this stage we don't want break compatibility with DSE 6.8.

Instead, we simply add `-XX:+IgnoreUnrecognizedVMOptions` which prevents JVM to fail to start due to unrecognized options - hence allowing Spark JobServer to run in both Java 8 and Java 11 without any changes.

In case we need to make changes required for DSE 6.9 which is Java 11, we should consider a new branch similarly to what we have done for Spark.

### CODE REVIEW

**Review by szymon-miezal — COMMENTED** [review]
I haven't (yet) found QA2 test results that would confirm that 6.8 jobserver starts correctly with this patch.

**Comment by tiagomlalves** [comment]
@szymon-miezal test results can be found in the draft patch that change bdp version:
* https://github.com/riptano/bdp/pull/21181 ([QA2_SparkWorkload #1861](https://jenkins-automaton.aws.dsinternal.org/job/QA2_SparkWorkload/1861/)) : ✅ 
* https://github.com/riptano/bdp/pull/21182 ([QA2_SparkWorkload #1862](https://jenkins-automaton.aws.dsinternal.org/job/QA2_SparkWorkload/1862/)) : ⚠️ tests are running, Spark JobServer is started, but tests fail

Note, to allow these tests in DSE 6.9 we're still relying on automaton branch from https://github.com/riptano/automaton/pull/5492 which I'll be finishing last.

**Review by szymon-miezal — APPROVED** [review]
The usage of `-XX:+IgnoreUnrecognizedVMOptions` makes sense to me, it should allow it to run under both JDK 8 and 11 for a while.

Ideally, we could detect JVM version and adjust the options dynamically but it would require more effort and I am not convinced whether it would provide much value.

IIUC the test failures are unrelated and will be fixed in subsequent patches.

**Comment by tiagomlalves** [comment]
I've added `0.8.0.56` tag and triggered https://jenkins-dse.aws.dsinternal.org/job/dse_spark_jobserver/75/ 
I'll be updating https://github.com/riptano/bdp/pull/21181 and https://github.com/riptano/bdp/pull/21182

**Pull request merged**
