### PR TITLE
DSP-22562 stop excluding netty from package 

### PR DESCRIPTION
**Pull request by shunsaker**
DSP-22562 stop excluding netty from package

Netty was being explicitly excluded so that DSE's version would be picked up
To fix https://github.com/advisories/GHSA-p979-4mfw-53vg DSE has removed it's dependency on Netty 3.9.9
spark-jobserver can't get rid of it's netty dependency entirely because no version of Akka has upgrade beyond netty 3.10.6
By packaging this version of netty into the spark-jobserver jar it can be removed as a direct dependency of DSE

### CODE REVIEW

**Comment by shunsaker** [comment]
Branch build with 3 failing tests https://jenkins-dse.aws.dsinternal.org/view/all/job/dse_spark_jobserver/54/
Root build with same 3 failing tests https://jenkins-dse.aws.dsinternal.org/view/all/job/dse_spark_jobserver/52/

**Review by tlasica — COMMENTED** [review]
Please make the commit more detailed.
As a reader I completely do not understand the changes:
I see some removals of "exclusions" why i was expecting the opposite :-)

After a while (in the morning) I realized it is something like:

```
we are not excluding netty from jobserver dependenceis
so that it will use ..... and not .... provided via ....

As the effect Netty 3.9.9 is ..
```

So the context of the change, rationale, impact on jobserver.

**Comment by thobe** [comment]
These changes make sense to me, but I agree with Tomek that the commit message needs to be more descriptive. For this change it is crucial that we describe what is being done, the intended effect of that, and the motivation for it.

**Comment by shunsaker** [comment]
Improved commit message

**Review by thobe — APPROVED** [review]
The new commit message looks great!

**Pull request merged**
